apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: document-ocr-service
spec:
  template:
    spec:
      containers:
        - image: northamerica-northeast1-docker.pkg.dev/document-ocr-480202/document-ocr-images/document-ocr-backend:latest
          env:
          ports:
            - containerPort: 4000